### ISSUE TITLE
Decryption not possible on different device

### ISSUE THREAD

**Issue by pepa65** [rfjakob/gocryptfs#219]
Not sure if this is a known issue, but on trying to decrypt a directory that I rsynced from my x86_64 laptop on to my bananapi (armv7l), the password gets rejected. There is an obvious difference in CPU architecture, and then there is a difference in go version. Would any of this explain a password not working when the directory is rsynced over??

Both freshly built according to the recommended recipe:
gocryptfs v1.4.4; go-fuse v20170619-31-ga9ddcb8; 2018-03-20 go1.9 (x86_64)
gocryptfs v1.4-48-g312ea32; go-fuse v20170619-14-g204b45d; 2018-03-19 go1.6.2 (armv7l)

[EDIT]
Also tried installing go1.9 on the bananapi:
gocryptfs v1.4-48-g312ea32; go-fuse v20170619-14-g204b45d; 2018-03-20 go1.9.2 (armv7l)

Still password not accepted... Is the different architecture causing this??

[EDIT]
Now rsynced the directory to yet another machine, and here it does decrypt...
gocryptfs v1.4.4; go-fuse v20170619-31-ga9ddcb8; 2018-03-20 go1.9.2 (x86_64)
(This is almost the same version as the original laptop...)

**Comment by rfjakob** [comment]
Hmmm. Do the self-tests pass on the bananapi? (./test.bash).

**Comment by pepa65** [comment]
OK, I run:
```
./build.bash
./test.bash
```
Output:
```
gocryptfs v1.4-48-g312ea32; go-fuse v20170619-14-g204b45d; 2018-03-20 go1.9.2
gocryptfs v1.4-48-g312ea32 without_openssl; go-fuse v20170619-14-g204b45d; 2018-03-20 go1.9.2
gocryptfs v1.4-48-g312ea32; go-fuse v20170619-14-g204b45d; 2018-03-20 go1.9.2
ok      github.com/rfjakob/gocryptfs    0.026s
?       github.com/rfjakob/gocryptfs/gocryptfs-xray     [no test files]
ok      github.com/rfjakob/gocryptfs/internal/configfile        7.863s
ok      github.com/rfjakob/gocryptfs/internal/contentenc        0.037s
ok      github.com/rfjakob/gocryptfs/internal/cryptocore        7.553s
ok      github.com/rfjakob/gocryptfs/internal/ctlsock   0.023s
?       github.com/rfjakob/gocryptfs/internal/exitcodes [no test files]
?       github.com/rfjakob/gocryptfs/internal/fusefrontend      [no test files]
?       github.com/rfjakob/gocryptfs/internal/fusefrontend_reverse      [no test files]
ok      github.com/rfjakob/gocryptfs/internal/nametransform     0.035s
?       github.com/rfjakob/gocryptfs/internal/nametransform/dirivcache  [no test files]
?       github.com/rfjakob/gocryptfs/internal/openfiletable     [no test files]
ok      github.com/rfjakob/gocryptfs/internal/pathiv    0.035s
ok      github.com/rfjakob/gocryptfs/internal/prefer_openssl    0.051s
ok      github.com/rfjakob/gocryptfs/internal/readpassword      0.142s
?       github.com/rfjakob/gocryptfs/internal/serialize_reads   [no test files]
ok      github.com/rfjakob/gocryptfs/internal/siv_aead  0.030s
ok      github.com/rfjakob/gocryptfs/internal/speed     0.024s [no tests to run]
ok      github.com/rfjakob/gocryptfs/internal/stupidgcm 26.195s
ok      github.com/rfjakob/gocryptfs/internal/syscallcompat     0.100s
?       github.com/rfjakob/gocryptfs/internal/tlog      [no test files]
2018/03/20 14:54:19 Unimplemented opcode POLL
Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.
-wpanic turns this warning into a panic: Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.
panic: -wpanic turns this warning into a panic: Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.


goroutine 22 [running]:
log.(*Logger).Panic(0x10d715f0, 0x10fbebf4, 0x1, 0x1)
        /usr/lib/go-1.9/src/log/log.go:212 +0x90
github.com/rfjakob/gocryptfs/internal/tlog.(*toggledLogger).Printf(0x10d66640, 0x1ff2cf, 0x9a, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/tlog/log.go:65 +0x194
github.com/rfjakob/gocryptfs/internal/syscallcompat.EnospcPrealloc.func1()
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/syscallcompat/sys_linux.go:31 +0x44
sync.(*Once).Do(0x314da0, 0x1ffebc)
        /usr/lib/go-1.9/src/sync/once.go:44 +0xb8
github.com/rfjakob/gocryptfs/internal/syscallcompat.EnospcPrealloc(0x5, 0x0, 0x0, 0x12, 0x0, 0x0, 0x2f0d58)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/syscallcompat/sys_linux.go:30 +0xb0
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).createHeader(0x10ef8000, 0x10d62028, 0x10d62028, 0x1, 0x2f0d58, 0x10d62028)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:121 +0x100
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).doWrite(0x10ef8000, 0x10efc32c, 0xb, 0x30, 0x0, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:274 +0xc1c
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).Write(0x10ef8000, 0x10efc32c, 0xb, 0x30, 0x0, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:369 +0x1d4
github.com/hanwen/go-fuse/fuse/pathfs.(*pathInode).Write(0x10eee060, 0x2f3138, 0x10ef8000, 0x10efc32c, 0xb, 0x30, 0x0, 0x0, 0x10efc2f4, 0x0, ...)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/pathfs/pathfs.go:736 +0x54
github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).Write(0x10d54340, 0x10efc2dc, 0x10efc32c, 0xb, 0x30, 0x5b, 0x5b)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:443 +0xc0
github.com/hanwen/go-fuse/fuse.doWrite(0x10ef40a0, 0x10efc1c0)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/opcode.go:168 +0x4c
github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0x10ef40a0, 0x10efc1c0, 0x10efc1c0)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:405 +0x23c
github.com/hanwen/go-fuse/fuse.(*Server).loop(0x10ef40a0, 0x10d0c001)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:377 +0x120
created by github.com/hanwen/go-fuse/fuse.(*Server).readRequest
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:285 +0x208
--- FAIL: TestPasswd (0.28s)
        cli_test.go:109: write /tmp/gocryptfs-test-parent/931562372/505331960.mnt/file1: software caused connection abort
2018/03/20 14:54:20 Unimplemented opcode POLL
Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.
-wpanic turns this warning into a panic: Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.
panic: -wpanic turns this warning into a panic: Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.


goroutine 1 [running]:
log.(*Logger).Panic(0x115635f0, 0x115348f8, 0x1, 0x1)
        /usr/lib/go-1.9/src/log/log.go:212 +0x90
github.com/rfjakob/gocryptfs/internal/tlog.(*toggledLogger).Printf(0x11554660, 0x1ff2cf, 0x9a, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/tlog/log.go:65 +0x194
github.com/rfjakob/gocryptfs/internal/syscallcompat.EnospcPrealloc.func1()
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/syscallcompat/sys_linux.go:31 +0x44
sync.(*Once).Do(0x314da0, 0x1ffebc)
        /usr/lib/go-1.9/src/sync/once.go:44 +0xb8
github.com/rfjakob/gocryptfs/internal/syscallcompat.EnospcPrealloc(0x3, 0x0, 0x0, 0x12, 0x0, 0x0, 0x2f0d58)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/syscallcompat/sys_linux.go:30 +0xb0
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).createHeader(0x116c8000, 0x1150e038, 0x1150e038, 0x1, 0x2f0d58, 0x1150e038)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:121 +0x100
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).doWrite(0x116c8000, 0x116e632c, 0xb, 0x30, 0x0, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:274 +0xc1c
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).Write(0x116c8000, 0x116e632c, 0xb, 0x30, 0x0, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:369 +0x1d4
github.com/hanwen/go-fuse/fuse/pathfs.(*pathInode).Write(0x11554060, 0x2f3138, 0x116c8000, 0x116e632c, 0xb, 0x30, 0x0, 0x0, 0x116e62f4, 0x0, ...)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/pathfs/pathfs.go:736 +0x54
github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).Write(0x115a2320, 0x116e62dc, 0x116e632c, 0xb, 0x30, 0x5b, 0x5b)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:443 +0xc0
github.com/hanwen/go-fuse/fuse.doWrite(0x116c20a0, 0x116e61c0)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/opcode.go:168 +0x4c
github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0x116c20a0, 0x116e61c0, 0x116e61c0)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:405 +0x23c
github.com/hanwen/go-fuse/fuse.(*Server).loop(0x116c20a0, 0x0)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:377 +0x120
github.com/hanwen/go-fuse/fuse.(*Server).Serve(0x116c20a0)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:325 +0x44
main.doMount(0x115700a0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/mount.go:147 +0x538
main.main()
        /home/pp/go/src/github.com/rfjakob/gocryptfs/main.go:267 +0x410
--- FAIL: TestPasswdMasterkey (0.30s)
        cli_test.go:151: write /tmp/gocryptfs-test-parent/931562372/709439991.mnt/file1: software caused connection abort
FAIL
FAIL    github.com/rfjakob/gocryptfs/tests/cli  3.975s
2018/03/20 14:54:30 Unimplemented opcode POLL
Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.
-wpanic turns this warning into a panic: Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.
panic: -wpanic turns this warning into a panic: Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.


goroutine 1 [running]:
log.(*Logger).Panic(0x121635f0, 0x121c18f8, 0x1, 0x1)
        /usr/lib/go-1.9/src/log/log.go:212 +0x90
github.com/rfjakob/gocryptfs/internal/tlog.(*toggledLogger).Printf(0x12154660, 0x1ff2cf, 0x9a, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/tlog/log.go:65 +0x194
github.com/rfjakob/gocryptfs/internal/syscallcompat.EnospcPrealloc.func1()
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/syscallcompat/sys_linux.go:31 +0x44
sync.(*Once).Do(0x314da0, 0x1ffebc)
        /usr/lib/go-1.9/src/sync/once.go:44 +0xb8
github.com/rfjakob/gocryptfs/internal/syscallcompat.EnospcPrealloc(0x9, 0x0, 0x0, 0x12, 0x0, 0x0, 0x2f0d58)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/syscallcompat/sys_linux.go:30 +0xb0
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).createHeader(0x122b0120, 0x1210e038, 0x1210e038, 0x1, 0x2f0d58, 0x1210e038)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:121 +0x100
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).doWrite(0x122b0120, 0x121724ec, 0x3, 0x30, 0x0, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:274 +0xc1c
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).Write(0x122b0120, 0x121724ec, 0x3, 0x30, 0x0, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:369 +0x1d4
github.com/hanwen/go-fuse/fuse/pathfs.(*pathInode).Write(0x1229e1a0, 0x2f3138, 0x122b0120, 0x121724ec, 0x3, 0x30, 0x0, 0x0, 0x121724b4, 0x0, ...)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/pathfs/pathfs.go:736 +0x54
github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).Write(0x12155300, 0x1217249c, 0x121724ec, 0x3, 0x30, 0x53, 0x53)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:443 +0xc0
github.com/hanwen/go-fuse/fuse.doWrite(0x12170280, 0x12172380)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/opcode.go:168 +0x4c
github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0x12170280, 0x12172380, 0x12172380)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:405 +0x23c
github.com/hanwen/go-fuse/fuse.(*Server).loop(0x12170280, 0x0)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:377 +0x120
github.com/hanwen/go-fuse/fuse.(*Server).Serve(0x12170280)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:325 +0x44
main.doMount(0x121700a0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/mount.go:147 +0x538
main.main()
        /home/pp/go/src/github.com/rfjakob/gocryptfs/main.go:267 +0x410
--- FAIL: TestOpenTruncateRead (0.01s)
        main_test.go:57: write /tmp/gocryptfs-test-parent/313724004/default-plain/TestTruncateWrite: software caused connection abort
--- FAIL: TestWORead (0.00s)
        main_test.go:97: open /tmp/gocryptfs-test-parent/313724004/default-plain/TestWORead: transport endpoint is not connected
--- FAIL: TestXfs124 (0.00s)
        main_test.go:119: open /tmp/gocryptfs-test-parent/313724004/default-plain/TestXfs124: transport endpoint is not connected
--- FAIL: TestWrite0200File (0.00s)
        main_test.go:170: creating empty file failed: open /tmp/gocryptfs-test-parent/313724004/default-plain/TestWrite0200File: transport endpoint is not connected
FAIL
FAIL    github.com/rfjakob/gocryptfs/tests/defaults     1.443s
ok      github.com/rfjakob/gocryptfs/tests/example_filesystems  25.759s
ok      github.com/rfjakob/gocryptfs/tests/hkdf_sanity  0.568s
2018/03/20 14:54:54 Unimplemented opcode POLL
Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.
-wpanic turns this warning into a panic: Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.
panic: -wpanic turns this warning into a panic: Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.


goroutine 1 [running]:
log.(*Logger).Panic(0x123735f0, 0x123348f8, 0x1, 0x1)
        /usr/lib/go-1.9/src/log/log.go:212 +0x90
github.com/rfjakob/gocryptfs/internal/tlog.(*toggledLogger).Printf(0x12368640, 0x1ff2cf, 0x9a, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/tlog/log.go:65 +0x194
github.com/rfjakob/gocryptfs/internal/syscallcompat.EnospcPrealloc.func1()
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/syscallcompat/sys_linux.go:31 +0x44
sync.(*Once).Do(0x314da0, 0x1ffebc)
        /usr/lib/go-1.9/src/sync/once.go:44 +0xb8
github.com/rfjakob/gocryptfs/internal/syscallcompat.EnospcPrealloc(0x5, 0x0, 0x0, 0x12, 0x0, 0x0, 0x2f0d58)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/syscallcompat/sys_linux.go:30 +0xb0
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).createHeader(0x123d4000, 0x12364028, 0x12364028, 0x1, 0x2f0d58, 0x12364028)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:121 +0x100
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).doWrite(0x123d4000, 0x123844ec, 0xa, 0x30, 0x0, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:274 +0xc1c
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).Write(0x123d4000, 0x123844ec, 0xa, 0x30, 0x0, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:369 +0x1d4
github.com/hanwen/go-fuse/fuse/pathfs.(*pathInode).Write(0x12354040, 0x2f3138, 0x123d4000, 0x123844ec, 0xa, 0x30, 0x0, 0x0, 0x123844b4, 0x0, ...)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/pathfs/pathfs.go:736 +0x54
github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).Write(0x123692e0, 0x1238449c, 0x123844ec, 0xa, 0x30, 0x5a, 0x5a)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:443 +0xc0
github.com/hanwen/go-fuse/fuse.doWrite(0x12382280, 0x12384380)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/opcode.go:168 +0x4c
github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0x12382280, 0x12384380, 0x12384380)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:405 +0x23c
github.com/hanwen/go-fuse/fuse.(*Server).loop(0x12382280, 0x0)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:377 +0x120
github.com/hanwen/go-fuse/fuse.(*Server).Serve(0x12382280)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:325 +0x44
main.doMount(0x123820a0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/mount.go:147 +0x538
main.main()
        /home/pp/go/src/github.com/rfjakob/gocryptfs/main.go:267 +0x410
ReadFile: open /tmp/gocryptfs-test-parent/050997110/default-plain/10: transport endpoint is not connected
--- FAIL: TestWrite10 (0.03s)
        matrix_test.go:90: err="write /tmp/gocryptfs-test-parent/050997110/default-plain/10: software caused connection abort", written=0
        matrix_test.go:94: close /tmp/gocryptfs-test-parent/050997110/default-plain/10: transport endpoint is not connected
        helpers.go:215: ReadFile failed: open /tmp/gocryptfs-test-parent/050997110/default-plain/10: transport endpoint is not connected
        helpers.go:222: Stat failed: stat /tmp/gocryptfs-test-parent/050997110/default-plain/10: transport endpoint is not connected
        matrix_test.go:104: Wrong content, hashWant=a63c90cc3684ad8b0a2176a6a8fe9005 hashActual=
--- FAIL: TestWrite100 (0.00s)
        matrix_test.go:84: open /tmp/gocryptfs-test-parent/050997110/default-plain/100: transport endpoint is not connected
--- FAIL: TestWrite1M (0.00s)
        matrix_test.go:84: open /tmp/gocryptfs-test-parent/050997110/default-plain/1M: transport endpoint is not connected
--- FAIL: TestWrite100x100 (0.00s)
        matrix_test.go:84: open /tmp/gocryptfs-test-parent/050997110/default-plain/100x100: transport endpoint is not connected
--- FAIL: TestTruncate (0.00s)
--- FAIL: TestFallocate (0.00s)
--- FAIL: TestAppend (0.00s)
--- FAIL: TestFileHoles (0.00s)
        matrix_test.go:378: file create failed
        matrix_test.go:385: open /tmp/gocryptfs-test-parent/050997110/default-plain/fileholes: transport endpoint is not connected
--- FAIL: TestRmwRace (0.00s)
        matrix_test.go:406: file create failed
--- FAIL: TestFiltered (0.00s)
        matrix_test.go:476: open /tmp/gocryptfs-test-parent/050997110/default-plain/gocryptfs.conf: transport endpoint is not connected
        matrix_test.go:484: remove /tmp/gocryptfs-test-parent/050997110/default-plain/gocryptfs.conf: transport endpoint is not connected
--- FAIL: TestFilenameEncryption (0.00s)
        matrix_test.go:492: open /tmp/gocryptfs-test-parent/050997110/default-plain/TestFilenameEncryption.txt: transport endpoint is not connected
--- FAIL: TestDirOverwrite (0.00s)
        matrix_test.go:518: mkdir /tmp/gocryptfs-test-parent/050997110/default-plain/DirOverwrite1: transport endpoint is not connected
--- FAIL: TestLongNames (0.00s)
        matrix_test.go:541: Could not create n255x: open /tmp/gocryptfs-test-parent/050997110/default-plain/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: transport endpoint is not connected
--- FAIL: TestLongLink (0.00s)
        matrix_test.go:621: open /tmp/gocryptfs-test-parent/050997110/default-plain/TestLongLink.target: transport endpoint is not connected
--- FAIL: TestLchown (0.00s)
        matrix_test.go:635: symlink /target/does/not/exist /tmp/gocryptfs-test-parent/050997110/default-plain/symlink: transport endpoint is not connected
--- FAIL: TestUtimesNanoSymlink (0.00s)
        matrix_test.go:652: symlink /some/nonexisting/file /tmp/gocryptfs-test-parent/050997110/default-plain/utimesnano_symlink: transport endpoint is not connected
--- FAIL: TestUtimesNano (0.00s)
        matrix_test.go:730: open /tmp/gocryptfs-test-parent/050997110/default-plain/utimesnano: transport endpoint is not connected
--- FAIL: TestUtimesNanoFd (0.00s)
        matrix_test.go:740: open /tmp/gocryptfs-test-parent/050997110/default-plain/utimesnanofd: transport endpoint is not connected
FAIL
FAIL    github.com/rfjakob/gocryptfs/tests/matrix       0.345s
2018/03/20 14:55:00 Unimplemented opcode POLL
Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.
-wpanic turns this warning into a panic: Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.
panic: -wpanic turns this warning into a panic: Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.


goroutine 10 [running]:
log.(*Logger).Panic(0x118655f0, 0x11885bf4, 0x1, 0x1)
        /usr/lib/go-1.9/src/log/log.go:212 +0x90
github.com/rfjakob/gocryptfs/internal/tlog.(*toggledLogger).Printf(0x11856660, 0x1ff2cf, 0x9a, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/tlog/log.go:65 +0x194
github.com/rfjakob/gocryptfs/internal/syscallcompat.EnospcPrealloc.func1()
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/syscallcompat/sys_linux.go:31 +0x44
sync.(*Once).Do(0x314da0, 0x1ffebc)
        /usr/lib/go-1.9/src/sync/once.go:44 +0xb8
github.com/rfjakob/gocryptfs/internal/syscallcompat.EnospcPrealloc(0x5, 0x0, 0x0, 0x12, 0x0, 0x0, 0x2f0d58)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/syscallcompat/sys_linux.go:30 +0xb0
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).createHeader(0x119d6000, 0x1180e038, 0x1180e038, 0x1, 0x2f0d58, 0x1180e038)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:121 +0x100
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).doWrite(0x119d6000, 0x119fc4ec, 0x3, 0x30, 0x0, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:274 +0xc1c
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).Write(0x119d6000, 0x119fc4ec, 0x3, 0x30, 0x0, 0x0, 0x0, 0x0)
        /home/pp/go/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:369 +0x1d4
github.com/hanwen/go-fuse/fuse/pathfs.(*pathInode).Write(0x119ca0a0, 0x2f3138, 0x119d6000, 0x119fc4ec, 0x3, 0x30, 0x0, 0x0, 0x119fc4b4, 0x0, ...)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/pathfs/pathfs.go:736 +0x54
github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).Write(0x119ca320, 0x119fc49c, 0x119fc4ec, 0x3, 0x30, 0x53, 0x53)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:443 +0xc0
github.com/hanwen/go-fuse/fuse.doWrite(0x119cc0a0, 0x119fc380)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/opcode.go:168 +0x4c
github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0x119cc0a0, 0x119fc380, 0x119fc380)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:405 +0x23c
github.com/hanwen/go-fuse/fuse.(*Server).loop(0x119cc0a0, 0x119d2001)
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:377 +0x120
created by github.com/hanwen/go-fuse/fuse.(*Server).readRequest
        /home/pp/go/src/github.com/hanwen/go-fuse/fuse/server.go:285 +0x208
--- FAIL: TestFiltered (0.01s)
        plaintextnames_test.go:72: write /tmp/gocryptfs-test-parent/073026431/838554322.mnt/gocryptfs.diriv: software caused connection abort
        plaintextnames_test.go:76: mkdir /tmp/gocryptfs-test-parent/073026431/838554322.mnt/664009225: transport endpoint is not connected
FAIL
FAIL    github.com/rfjakob/gocryptfs/tests/plaintextnames       0.489s
ok      github.com/rfjakob/gocryptfs/tests/reverse      1.730s
?       github.com/rfjakob/gocryptfs/tests/test_helpers [no test files]
```

**Comment by rfjakob** [comment]
Bananapi: Are you sure /tmp is on ext4?
> Warning: The underlying filesystem does not support fallocate(2). gocryptfs will continue working but is no longer resistant against out-of-space errors.

But this is was what I was looking for:
> ok      github.com/rfjakob/gocryptfs/tests/example_filesystems  25.759s

This means the example filesystems (that were created on x86_64) mount ok.

Hmm. Does mounting a fs created on the bananapi work on x86_64?

**Comment by rfjakob** [comment]
Btrfs: this looks like a bug in the tests (file is not closed before unmount)
> fusermount: failed to unmount /tmp/gocryptfs-test-parent/886124527/v0.7-plaintextnames.mnt: Device or resource busy

**Comment by pepa65** [comment]
On the bananapi /tmp is on tmpfs.

**Comment by rfjakob** [comment]
You must be running a very old kernel, tmpfs supports fallocate since kernel v3.5, released 2012 ([kernel commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e2d12e22c59c)).

A gocryptfs filesystem is supposed to be 100% portable across different CPUs, strange. Your board is a bananapi m1 like this? https://www.aliexpress.com/store/product/Original-Banana-Pi-A20-M1-Dual-Core-1GB-RAM-Open-source-development-board-BPI-M1/302756_32806385403.html?spm=2114.12010612.0.0.42c84578NnAqxx

**Comment by pepa65** [comment]
Yes, it's a first generation M1. I depend on what images get provided. This kernel is 3.4.112-sun7i...

**Comment by rfjakob** [comment]
I have access to an allwinner a31, which is also a cortex-a7, and i'll see if i can reproduce the problem.

Neither the different gocryptfs version nor the old kernel should cause a problem like this.

One more thing you could try in the meantime: use "-passfile=pwd.txt" instead of entering the password manually.

**Comment by pepa65** [comment]
Wait, I made a mistake with changing the permissions, and my wrapper script didn't pass on the actual error message. I now managed to mount the copy. Very sorry for causing you to spend time on this non-error. At least I know now that gocryptfs is supposed to be portable, and by all indications is...

**Comment by rfjakob** [comment]
Ok good, I was worried a little already ;)
