### ISSUE TITLE
Revisit macOS syscall emulation code

### ISSUE THREAD

**Issue by slackner** [rfjakob/gocryptfs#307]
As mentioned in https://github.com/rfjakob/gocryptfs/commit/b26080bf96b85179d7dec37cb10bda43b53fd7e8#r31812909, the `sys/unix` package now contains most of the syscalls required by gocryptfs even for macOS. This should allow to reduce the syscall emulation code (only a few functions are still required) and improve performance on macOS.

**Comment by rfjakob** [comment]
Good idea, my problem with MacOS changes is that I don't have a machine to test

**Comment by slackner** [comment]
Unfortunately I also cannot easily test on macOS. Maybe we should add the 'help wanted' tag, it would definitely be useful to get some more macOS developers involved in gocryptfs.

Another option might be to use Travis CI for the OSX tests. Recent documentations suggest that OSX support is available for open-source projects:

https://docs.travis-ci.com/user/reference/osx/
https://docs.travis-ci.com/user/multi-os/

`go` is explicitly listed as supported language.

**Comment by rfjakob** [comment]
Travis may really work if we manage to install OSXFUSE:

> Passwordless sudo is available

**Comment by rfjakob** [comment]
Looks like these people got it to work:

https://github.com/bazelbuild/sandboxfs/blob/master/admin/travis-install.sh#L30

**Comment by slackner** [comment]
Okay, good and bad news. The good one: I now have a mac machine available for testing and debugging. The bad one: Current versions of gocryptfs are pretty much broken on macOS. In forward mode, mountpoints cannot be accessed at all - you always get `invalid argument`. The first few fixes seem pretty easy, so maybe I can get them done today. Nevertheless, to avoid unnecessary rebasing work, it would be good if we could soon come up with a decision regarding the `seteuid` stuff. ;)

**Comment by slackner** [comment]
Remaining issues after the `Faccessat` fix:

```
$ ./test-without-openssl.bash 
Using TMPDIR=/var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/
flock is not available, skipping
gocryptfs v1.7-rc1-31-g116938c without_openssl; go-fuse v20170619-77-g425e8d5; 2019-01-12 go1.11.4
ok  	github.com/rfjakob/gocryptfs	0.008s
?   	github.com/rfjakob/gocryptfs/gocryptfs-xray	[no test files]
ok  	github.com/rfjakob/gocryptfs/gocryptfs-xray/xray_tests	0.055s
ok  	github.com/rfjakob/gocryptfs/internal/configfile	2.470s
ok  	github.com/rfjakob/gocryptfs/internal/contentenc	0.013s
ok  	github.com/rfjakob/gocryptfs/internal/cryptocore	0.636s
ok  	github.com/rfjakob/gocryptfs/internal/ctlsock	0.010s
?   	github.com/rfjakob/gocryptfs/internal/ensurefds012	[no test files]
?   	github.com/rfjakob/gocryptfs/internal/exitcodes	[no test files]
ok  	github.com/rfjakob/gocryptfs/internal/fusefrontend	0.068s
ok  	github.com/rfjakob/gocryptfs/internal/fusefrontend_reverse	0.010s
ok  	github.com/rfjakob/gocryptfs/internal/nametransform	0.010s
?   	github.com/rfjakob/gocryptfs/internal/openfiletable	[no test files]
ok  	github.com/rfjakob/gocryptfs/internal/pathiv	0.009s
ok  	github.com/rfjakob/gocryptfs/internal/prefer_openssl	0.009s
ok  	github.com/rfjakob/gocryptfs/internal/readpassword	0.075s
?   	github.com/rfjakob/gocryptfs/internal/serialize_reads	[no test files]
ok  	github.com/rfjakob/gocryptfs/internal/siv_aead	0.008s
ok  	github.com/rfjakob/gocryptfs/internal/speed	0.008s [no tests to run]
?   	github.com/rfjakob/gocryptfs/internal/stupidgcm	[no test files]
--- FAIL: TestFchmodat (0.00s)
    sys_common_test.go:81: chmod on symlink should have failed, but did not. New mode=0755
    sys_common_test.go:86: chmod on symlink affected symlink target: New mode=0333
FAIL
FAIL	github.com/rfjakob/gocryptfs/internal/syscallcompat	0.014s
ok  	github.com/rfjakob/gocryptfs/internal/tlog	0.008s
UnmountErr: "/var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/428192370/003347453.mnt" was not found in MountInfo, cannot check for FD leaks
UnmountErr: "/var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/428192370/573676842.mnt" was not found in MountInfo, cannot check for FD leaks
--- FAIL: TestComma (0.05s)
    cli_test.go:534: Failed to mount "/var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/428192370/049415809,foo,bar" on "/var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/428192370/049415809,foo,bar.mnt": exit status 19
FAIL
FAIL	github.com/rfjakob/gocryptfs/tests/cli	2.540s
--- FAIL: TestMvWarningSymlink (0.01s)
    main_test.go:234: mv: cannot resolve /var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/612829454/default-plain/TestMvWarningSymlink: /foo
        
    main_test.go:235: exit status 1
FAIL
FAIL	github.com/rfjakob/gocryptfs/tests/defaults	6.693s
Skipping OpenSSL tests, I have been compiled without openssl support
--- FAIL: TestExampleFSv07 (0.30s)
    helpers.go:242: mkdir /var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/676434804/v0.7/dir1: permission denied
    helpers.go:242: mkdir /var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/676434804/v0.7/dir1: permission denied
--- FAIL: TestExampleFSv09 (0.26s)
    helpers.go:242: mkdir /var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/676434804/v0.9/dir1: permission denied
    helpers.go:242: mkdir /var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/676434804/v0.9.2/dir1: permission denied
--- FAIL: TestExampleFSv11 (0.24s)
    helpers.go:242: mkdir /var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/676434804/v1.1-aessiv/dir1: permission denied
    helpers.go:242: mkdir /var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/676434804/v1.1-aessiv.2/dir1: permission denied
--- FAIL: TestExampleFSv13 (0.25s)
    helpers.go:242: mkdir /var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/676434804/v1.3/dir1: permission denied
    helpers.go:242: mkdir /var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/676434804/v1.3_m/dir1: permission denied
UnmountErr: "/var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/676434804/TestExampleFSv13MasterkeyStdin.mnt" was not found in MountInfo, cannot check for FD leaks
--- FAIL: TestExampleFSv13MasterkeyStdin (0.13s)
    helpers.go:242: mkdir /var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/676434804/TestExampleFSv13MasterkeyStdin.mnt/dir1: permission denied
FAIL
FAIL	github.com/rfjakob/gocryptfs/tests/example_filesystems	4.506s
ok  	github.com/rfjakob/gocryptfs/tests/fsck	0.863s
ok  	github.com/rfjakob/gocryptfs/tests/hkdf_sanity	0.245s
--- FAIL: TestUtimesNano (0.00s)
    matrix_test.go:628: no such file or directory
FAIL
FAIL	github.com/rfjakob/gocryptfs/tests/matrix	3.311s
ok  	github.com/rfjakob/gocryptfs/tests/plaintextnames	0.162s
name="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" err=no such file or directory2019/01/12 15:55:54 inconsistent result on "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": stat=true open=true readdir=false, path="/var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/952426083/c/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
--- FAIL: TestLongnameStat (1.02s)
panic: inconsistent result on "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": stat=true open=true readdir=false, path="/var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/952426083/c/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" [recovered]
	panic: inconsistent result on "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": stat=true open=true readdir=false, path="/var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/952426083/c/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

goroutine 18 [running]:
testing.tRunner.func1(0xc000112100)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:792 +0x387
panic(0x11b5740, 0xc0000b2050)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
log.Panicf(0x120c98a, 0x3e, 0xc00003fde0, 0x5, 0x5)
	/usr/local/Cellar/go/1.11.4/libexec/src/log/log.go:333 +0xda
github.com/rfjakob/gocryptfs/tests/test_helpers.VerifyExistence(0xc0003185a0, 0xe9, 0x0)
	/Users/admin/go/src/github.com/rfjakob/gocryptfs/tests/test_helpers/helpers.go:311 +0x392
github.com/rfjakob/gocryptfs/tests/reverse_test.TestLongnameStat(0xc000112100)
	/Users/admin/go/src/github.com/rfjakob/gocryptfs/tests/reverse/correctness_test.go:29 +0x3eb
testing.tRunner(0xc000112100, 0x120e2e8)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:878 +0x35c
FAIL	github.com/rfjakob/gocryptfs/tests/reverse	1.402s
?   	github.com/rfjakob/gocryptfs/tests/symlink_race	[no test files]
?   	github.com/rfjakob/gocryptfs/tests/test_helpers	[no test files]
ok  	github.com/rfjakob/gocryptfs/tests/trezor	0.025s
DecryptBlock: Block is too short: 3 bytes
DecryptBlock: Block is too short: 2 bytes
GetXAttr: Block is too short
GetXAttr: cipher: message authentication failed
GetXAttr: cipher: message authentication failed
GetXAttr: cipher: message authentication failed
--- FAIL: TestList0000File (0.00s)
    xattr_integration_test.go:303: xattr.list /var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/952090213/default-plain/TestList0000File : permission denied
--- FAIL: TestList0000Dir (0.00s)
    xattr_integration_test.go:325: creating directory failed: permission denied
--- FAIL: TestSet0200Dir (0.00s)
    xattr_integration_test.go:339: creating directory failed: permission denied
FAIL
FAIL	github.com/rfjakob/gocryptfs/tests/xattr	0.252s
```

**Comment by slackner** [comment]
I did some more testing, and we can indeed get rid of most of the emulation code. The syscall wrappers provided in the `sys/unix` package seem to be working fine (for simplicity, I just replaced them in `sys_darwin.go`).

Should we use the `unix` package directly everywhere, or keep the `syscallcompat` intermediate layer (e.g., for parameter validation)? And what about the emulation code and tests - move them to `sys_common_test.go`? BTW: If you have any patches for testing, please let me know.

**Comment by rfjakob** [comment]
Looking at https://www.gosquared.com/global/mac/sierra/#launch , there are still 5% of people running Mavericks = MacOS 10.9, probably because Apple has dropped support for their hardware.

However, looking at https://github.com/golang/go/wiki/Darwin , Go itself has dropped support for 10.9 and lower. And the [Go download page](https://golang.org/dl/) says "macOS 10.10 or later". Hmm.

**Comment by rfjakob** [comment]
> Should we use the unix package directly everywhere, or keep the syscallcompat intermediate layer (e.g., for parameter validation)?

In the first step, I would keep the syscallcompat layer.

> And what about the emulation code and tests - move them to sys_common_test.go?

Delete emulation code that is no longer used. Keep the test but run it against the actual syscall instead of the emulation code. The will give us some confidence that the MacOS syscalls work as expected.

**Comment by rfjakob** [comment]
Given that Go dropped support for MacOS 10.9 and lower, I think we should follow. We can depend on features from 10.10.

**Comment by rfjakob** [comment]
This is done as of Jan 2019:

commit a9d8eb49ef91c31fddc3e4f2f76e9b98e1a52a1d
Author: Sebastian Lackner <sebastian@fds-team.de>
Date:   Mon Jan 14 03:00:49 2019 +0100

    syscallcompat: Drop Fstatat emulation on macOS.

commit 4134ff7570906d38d519b1aad33cd3e97685e92f
Author: Sebastian Lackner <sebastian@fds-team.de>
Date:   Mon Jan 14 02:56:06 2019 +0100

    syscallcompat: Drop Mkdirat emulation on macOS.

commit 7b0d56fe98a4ae449d26af0b83d00271a179db6e
Author: Sebastian Lackner <sebastian@fds-team.de>
Date:   Mon Jan 14 02:51:50 2019 +0100

    syscallcompat: Drop Symlinkat emulation on macOS.

commit 92110628ee5f48b0106b32090854fcc61d6bca20
Author: Sebastian Lackner <sebastian@fds-team.de>
Date:   Mon Jan 14 02:49:11 2019 +0100

    syscallcompat: Drop Fchownat emulation on macOS.

commit 0345cc08307c01da635ea5546952a584480c9a93
Author: Sebastian Lackner <sebastian@fds-team.de>
Date:   Mon Jan 14 02:45:21 2019 +0100

    syscallcompat: Drop Fchmodat emulation on macOS.
    
    On macOS the function has a flags argument, so we don't need the
    /proc/self/fd trick used on Linux.

commit 229a9da74bc0839e2cd481f701c877708b080ede
Author: Sebastian Lackner <sebastian@fds-team.de>
Date:   Mon Jan 14 02:38:34 2019 +0100

    syscallcompat: Drop Unlinkat emulation on macOS.

commit 42bf6d1c68700a0d5d910c1be42088cc14125fec
Author: Sebastian Lackner <sebastian@fds-team.de>
Date:   Mon Jan 14 02:35:46 2019 +0100

    syscallcompat: Drop Renameat emulation on macOS.

commit da557702d713e38a8c6c4c28275724c70988f919
Author: Sebastian Lackner <sebastian@fds-team.de>
Date:   Mon Jan 14 02:32:28 2019 +0100

    syscallcompat: Drop Openat emulation on macOS.
