### ISSUE TITLE
MacOS: test failure in TestLongnameStat

### ISSUE THREAD

**Issue by slackner** [rfjakob/gocryptfs#351]
```
name="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" err=no such file or directory2019/01/15 10:52:52 inconsistent result on "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx":
  stat=true open=true readdir=false, path="/var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/616241126/c/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
--- FAIL: TestLongnameStat (1.02s)
panic: inconsistent result on "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx":
  stat=true open=true readdir=false, path="/var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/616241126/c/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" [recovered]
	panic: inconsistent result on "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": stat=true open=true readdir=false, path="/var/folders/6x/tlqzyq0j38j9xw6qkl8p3jcm0000gq/T/gocryptfs-test-parent/616241126/c/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

goroutine 12 [running]:
testing.tRunner.func1(0xc000010800)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:792 +0x387
panic(0x11b57c0, 0xc00001c8b0)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
log.Panicf(0x120ca63, 0x3e, 0xc000043de0, 0x5, 0x5)
	/usr/local/Cellar/go/1.11.4/libexec/src/log/log.go:333 +0xda
github.com/rfjakob/gocryptfs/tests/test_helpers.VerifyExistence(0xc0002ea0e0, 0xd9, 0x0)
	/Users/admin/go/src/github.com/rfjakob/gocryptfs/tests/test_helpers/helpers.go:311 +0x392
github.com/rfjakob/gocryptfs/tests/reverse_test.TestLongnameStat(0xc000010800)
	/Users/admin/go/src/github.com/rfjakob/gocryptfs/tests/reverse/correctness_test.go:29 +0x3eb
testing.tRunner(0xc000010800, 0x120e380)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:878 +0x35c
FAIL	github.com/rfjakob/gocryptfs/tests/reverse	1.208s
```

Note that the number of 'x's seem to vary from run to run (e.g., compare with https://github.com/rfjakob/gocryptfs/pull/343), which suggests it is timing or cache related. The issue needs further investigations.

**Comment by slackner** [comment]
Output with `-fusedebug` and `-d`:
https://gist.githubusercontent.com/slackner/ca6a69b8886faf9fba3fafd32d7e2f5c/raw/0f5e117898f6d4189a76ce95739a43a02f0b1af1/gistfile1.txt

**Comment by rfjakob** [comment]
`stat=true open=true readdir=false` means the file could be `stat()`ed, it could be `open()`ed, but it did NOT show up in the directory listing. If this is nondeterministic, it's gonna be a hard one, because the test has two filesystems mounted on top of each other.

**Comment by slackner** [comment]
Suspicious parts of the log:

```
2019/01/15 12:02:45 rx 5: LOOKUP i1 ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"] 252b
FS.GetAttr("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
2019/01/15 12:02:45 rx 4: LOOKUP i1 ["gocryptfs.longname.iNPx_rqvgCZCkSHiDxThVRUMDqfqDYPSMcu58uAVTdA"] 63b
2019/01/15 12:02:45 tx 4:     OK, {i330 g329 tE=1s tA=1s {M0100644 SZ=0 L=1 503:204 0 0:3182331 A 1547582565.000000 M 1547582565.000000 C 1547582565.000000}}
[...]
2019/01/15 12:02:45 rx 4: OPEN i330 {O_RDONLY} 
2019/01/15 12:02:45 tx 4:     OK, {Fh 3 }
[...]
2019/01/15 12:02:45 rx 2: RELEASE i330 {Fh 3   L0} 
2019/01/15 12:02:45 tx 2:     OK
[...]
2019/01/15 12:02:45 rx 5: OPENDIR i1 
OpenDir()
[...]
2019/01/15 12:02:45 rx 3: READDIR i1 {Fh 2 [0 +6553) } 
2019/01/15 12:02:45 tx 3:     OK,  328b data "\u038d0\x00\x00\x00\x00\x00"...
2019/01/15 12:02:45 rx 2: READDIR i1 {Fh 2 [6 +6553) } 
2019/01/15 12:02:45 tx 2:     OK
```

Note that at the point when `READDIR` is called, the `OPENDIR` has not finished yet. Instead the kernel either (intentionally or unintentionally) uses an existing directory handle. Since the file wasn't present yet at that point the test fails.

Removing the `d.lastOffset > 0` condition in `go-fuse/fuse/nodefs/dir.go` fixes the issue:

```
	// rewinddir() should be as if reopening directory.
	// TODO - test this.
	if d.lastOffset > 0 && input.Offset == 0 {
		d.stream, code = d.node.OpenDir((*fuse.Context)(&input.Context))
		if !code.Ok() {
			return code
		}
	}
```

Nevertheless, of course this is only a very bad hack, since `OpenDir` is then effectively executed twice. So, the next question is, who exactly is making an incorrect assumption about reusing directory fds?

Unrelated, but I highly suspect that there is some `d.lastOffset = ...` missing in the following code block:

```
		// No need to fill attributes for . and ..
		if e.Name == "." || e.Name == ".." {
			continue
		}
```

**Comment by slackner** [comment]
After some more investigations, I believe that this is a bug in `go-fuse`. The code I already showed above differs significantly from `libfuse`:

Linux: https://github.com/libfuse/libfuse/blob/b8093eb57b5cf71dbe91dcb5cf5f8c86b1641752/lib/fuse.c#L3703
MacOS: https://github.com/osxfuse/fuse/blob/abc35f85fdede186ed164082bd71fc1217d2f58f/lib/fuse.c#L3983

In both cases, the code states that:

```
	/* According to SUS, directory contents need to be refreshed on
	   rewinddir() */
	if (!off)
		dh->filled = 0;

	if (!dh->filled) {
		err = readdir_fill(f, req, ino, size, off, dh, &fi, flags);
```

So the content should be queried on the first `readdir` call, not in `opendir`. On Linux this is apparently never a problem since the kernel does not reuse directory handles.

**Comment by slackner** [comment]
I think this bug can be safely marked as 'bug outside gocryptfs'. As you probably already saw, I opened a bug report at the `go-fuse` project with my analysis. I also just added a testcase that can be used to reproduce the incorrect behavior on Linux.

**Comment by rfjakob** [comment]
Will be fixed once https://github.com/hanwen/go-fuse/pull/254 is merged.
