### ISSUE TITLE
/bin/fusermount vs. /usr/bin/fusermount

### ISSUE THREAD

**Issue by G-A-N** [rfjakob/gocryptfs#448]
The most recent changeset introduced a bug/problem in `mount.go`: on my systems `fusermount` is under `/usr/bin/fusermount`.

Thanks.

**Comment by rfjakob** [comment]
Hi, and you now get a warning message?

**Comment by G-A-N** [comment]
Kind of. One test fails:

```warning: haveFusermount2: fork/exec /bin/fusermount: no such file or directory
-wpanic turns this warning into a panic: warning: haveFusermount2: fork/exec /bin/fusermount: no such file or directory
panic: -wpanic turns this warning into a panic: warning: haveFusermount2: fork/exec /bin/fusermount: no such file or directory

goroutine 1 [running]:
log.(*Logger).Panic(0xc0000ca280, 0xc0000c5680, 0x1, 0x1)
        /usr/lib64/go/1.11/src/log/log.go:212 +0xbe
github.com/rfjakob/gocryptfs/internal/tlog.(*toggledLogger).Printf(0xc0000a0780, 0x68ed95, 0x1c, 0xc0000c5700, 0x1, 0x1)
        github.com/rfjakob/gocryptfs/internal/tlog/log.go:78 +0x209
main.haveFusermount2(0x630b20)
        github.com/rfjakob/gocryptfs/mount.go:449 +0x132
main.initGoFuse(0x6c83a0, 0xc0000aa4e0, 0xc0000aa820, 0xc00006a8d0)
        github.com/rfjakob/gocryptfs/mount.go:368 +0x11f6
main.doMount(0xc0000aa820)
        github.com/rfjakob/gocryptfs/mount.go:121 +0x49a
main.main()
        github.com/rfjakob/gocryptfs/main.go:280 +0x46a
--- FAIL: TestNonempty (0.02s)
    mount_unmount.go:117: mount failed: exit status 2
UnmountErr: "/var/tmp/gocryptfs-test-parent-2203/278442541/532176376.mnt" was not found in MountInfo, cannot check for FD leaks
2020/01/13 22:06:39 Unimplemented opcode POLL
UnmountErr: "/var/tmp/gocryptfs-test-parent-2203/278442541/104917057.mnt" was not found in MountInfo, cannot check for FD leaks
FAIL
FAIL    github.com/rfjakob/gocryptfs/tests/cli  2.779s
```
Nothing terrible, but a failing test does not look nice. You should be able to reproduce the problem by simply using `/usr/bin/fusermount` (or any non-existing path) instead of `/bin/fusermount`.

**Comment by rfjakob** [comment]
Fixed, thanks!
