### ISSUE TITLE
`gocryptfs -speed` panics on go1.21

### ISSUE THREAD

**Issue by alex3d** [rfjakob/gocryptfs#789]
```
$ ./gocryptfs -speed
gocryptfs v2.4.0-2-g8b1c4b0-dirty without_openssl; go-fuse v2.3.0; 2023-09-15 go1.21.1 linux/amd64
cpu: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz; with AES acceleration
AES-GCM-256-OpenSSL             panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5a5d20]

goroutine 7 [running]:
testing.(*common).decorate(0x40d625?, {0xc00001c150, 0x2a}, 0x830601?)
        testing/testing.go:772 +0xa0
testing.(*common).logDepth(0xc00012c280, {0xc00001c150, 0x2a}, 0x3)
        testing/testing.go:1035 +0x1dd
testing.(*common).log(...)
        testing/testing.go:1004
testing.(*common).Skip(0xc00012c280, {0xc00003ef08?, 0x48874f?, 0xc00003ef18?})
        testing/testing.go:1089 +0x4a
github.com/rfjakob/gocryptfs/v2/internal/speed.bStupidGCM(0xc00012c280)
        github.com/rfjakob/gocryptfs/v2/internal/speed/speed.go:131 +0x45
testing.(*B).runN(0xc00012c280, 0x1)
        testing/benchmark.go:193 +0x102
testing.(*B).run1.func1()
        testing/benchmark.go:233 +0x4e
created by testing.(*B).run1 in goroutine 1
        testing/benchmark.go:226 +0x90
```

**Comment by rfjakob** [comment]
Bizarre. I saw this crash, but after a `git clean -dxff` I don't.

```
$ ./build.bash 
gocryptfs v2.4.0-2-gb362b11; go-fuse v2.3.0; 2023-09-15 go1.21.1 linux/amd64

$ ./gocryptfs -speed
gocryptfs v2.4.0-4-g7fff33a without_openssl; go-fuse v2.3.0; 2023-09-15 go1.21.1 linux/amd64
cpu: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz; with AES acceleration
AES-GCM-256-OpenSSL       	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5a5de0]

goroutine 7 [running]:
testing.(*common).decorate(0x40d625?, {0xc00001c180, 0x2a}, 0x830601?)
	testing/testing.go:772 +0xa0
testing.(*common).logDepth(0xc00012e280, {0xc00001c180, 0x2a}, 0x3)
	testing/testing.go:1035 +0x1dd
testing.(*common).log(...)
	testing/testing.go:1004
testing.(*common).Skip(0xc00012e280, {0xc000044f08?, 0x48874f?, 0xc000044f18?})
	testing/testing.go:1089 +0x4a
github.com/rfjakob/gocryptfs/v2/internal/speed.bStupidGCM(0xc00012e280)
	github.com/rfjakob/gocryptfs/v2/internal/speed/speed.go:129 +0x45
testing.(*B).runN(0xc00012e280, 0x1)
	testing/benchmark.go:193 +0x102
testing.(*B).run1.func1()
	testing/benchmark.go:233 +0x4e
created by testing.(*B).run1 in goroutine 1
	testing/benchmark.go:226 +0x90

$ git clean -dxff
Removing Documentation/gocryptfs-xray.1
Removing Documentation/gocryptfs.1
Removing Documentation/statfs.1
Removing a/
Removing contrib/atomicrename/atomicrename
Removing contrib/findholes/findholes
Removing contrib/statfs/statfs
Removing gocryptfs
Removing gocryptfs-xray/gocryptfs-xray
Removing gocryptfs_v2.4.0_linux-static_amd64.tar.gz
Removing gocryptfs_v2.4.0_linux-static_amd64.tar.gz.asc
Removing gocryptfs_v2.4.0_src-deps.tar.gz
Removing gocryptfs_v2.4.0_src-deps.tar.gz.asc
Removing gocryptfs_v2.4.0_src.tar.gz
Removing gocryptfs_v2.4.0_src.tar.gz.asc
Removing internal/configfile/config_test/tmp.conf
Removing tests/cli/cli.test
Removing tests/cluster/cluster.test
Removing tests/fsck/mnt/
Removing tests/root_test/root_test.test

$ ./build.bash 
gocryptfs v2.4.0-4-g7fff33a; go-fuse v2.3.0; 2023-09-15 go1.21.1 linux/amd64

$ ./gocryptfs -speed
gocryptfs v2.4.0-4-g7fff33a; go-fuse v2.3.0; 2023-09-15 go1.21.1 linux/amd64
cpu: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz; with AES acceleration
AES-GCM-256-OpenSSL       	 689.38 MB/s
AES-GCM-256-Go            	 993.14 MB/s	(selected in auto mode)
AES-SIV-512-Go            	 159.37 MB/s
XChaCha20-Poly1305-OpenSSL	 554.66 MB/s
XChaCha20-Poly1305-Go     	 844.00 MB/s	(selected in auto mode)
```

**Comment by rfjakob** [comment]
Looks like it explodes when built without openssl.

```
$ ./build-without-openssl.bash 
gocryptfs v2.4.0-4-g7fff33a without_openssl; go-fuse v2.3.0; 2023-09-15 go1.21.1 linux/amd64

$ ./gocryptfs -speed
gocryptfs v2.4.0-4-g7fff33a without_openssl; go-fuse v2.3.0; 2023-09-15 go1.21.1 linux/amd64
cpu: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz; with AES acceleration
AES-GCM-256-OpenSSL       	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5a5de0]

goroutine 7 [running]:
testing.(*common).decorate(0x40d625?, {0xc00001c180, 0x2a}, 0x830601?)
	testing/testing.go:772 +0xa0
testing.(*common).logDepth(0xc00012e280, {0xc00001c180, 0x2a}, 0x3)
	testing/testing.go:1035 +0x1dd
testing.(*common).log(...)
	testing/testing.go:1004
testing.(*common).Skip(0xc00012e280, {0xc000044f08?, 0x48874f?, 0xc000044f18?})
	testing/testing.go:1089 +0x4a
github.com/rfjakob/gocryptfs/v2/internal/speed.bStupidGCM(0xc00012e280)
	github.com/rfjakob/gocryptfs/v2/internal/speed/speed.go:129 +0x45
testing.(*B).runN(0xc00012e280, 0x1)
	testing/benchmark.go:193 +0x102
testing.(*B).run1.func1()
	testing/benchmark.go:233 +0x4e
created by testing.(*B).run1 in goroutine 1
	testing/benchmark.go:226 +0x90
```
