### ISSUE TITLE
2.4.0 Fails to build on M1 Sonoma 14.3

### ISSUE THREAD

**Issue by litori** [rfjakob/gocryptfs#823]
Ever since 2.4.0, gocryptfs fails to build on my M1 mac running on Sonoma 14.3.  Both build-without-openssl.bash and build.bash fails with the same error.

```% ./build-without-openssl.bash 
panic: XTIMES (80000000) overlaps with INIT_RESERVED (80000000)

goroutine 1 [running]:
github.com/hanwen/go-fuse/v2/fuse.(*flagNames).set(0x7?, 0x80000000, {0x104d2d9d3?, 0xffffffffffffffff?})
	github.com/hanwen/go-fuse/v2@v2.4.2/fuse/print.go:124 +0x150
github.com/hanwen/go-fuse/v2/fuse.init.1()
	github.com/hanwen/go-fuse/v2@v2.4.2/fuse/print_darwin.go:12 +0x34```

**Comment by yahesh** [comment]
I do have the same problem which seems to come from the updates go-fuse 2.4.2 version that was introduced in https://github.com/rfjakob/gocryptfs/commit/9958b63931aee613d5f97a8e7137efa3fb118343. Reverting this to go-fuse 2.4.0 fixes the problem for now.

It seems that this is [a know problem](https://geeksrepos.com/hanwen/go-fuse/issues/493) which got fixed fixed in go-fuse 2.5.0: https://github.com/hanwen/go-fuse/commit/aab5a0dd1b9eea289e9f0cda96a283baaa1b5d10

Maybe @rfjakob could bump the version go-fuse so resolve it for good.

**Comment by rfjakob** [comment]
Fixed, thanks @arrase !
